In [3]:
import pandas as pd

In [ ]:
pd.__version__
!pip  uninstall pyarrow

In [1]:
!pip uninstall pyarrow -y

Found existing installation: pyarrow 20.0.0
Uninstalling pyarrow-20.0.0:
  Successfully uninstalled pyarrow-20.0.0

In [4]:
df = pd.read_parquet("https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet")

In [5]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2.0,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186.0,79.0,2.0,17.70,1.00,0.5,0.00,0.00,1.0,22.70,2.5,0.0
1,1.0,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140.0,236.0,1.0,10.00,3.50,0.5,3.75,0.00,1.0,18.75,2.5,0.0
2,1.0,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236.0,79.0,1.0,23.30,3.50,0.5,3.00,0.00,1.0,31.30,2.5,0.0
3,1.0,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79.0,211.0,1.0,10.00,3.50,0.5,2.00,0.00,1.0,17.00,2.5,0.0
4,1.0,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211.0,148.0,1.0,7.90,3.50,0.5,3.20,0.00,1.0,16.10,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2964619,2.0,2024-01-31 23:45:59,2024-01-31 23:54:36,NaN,3.18,NaN,None,107.0,263.0,0.0,15.77,0.00,0.5,2.00,0.00,1.0,21.77,NaN,NaN
2964620,1.0,2024-01-31 23:13:07,2024-01-31 23:27:52,NaN,4.00,NaN,None,114.0,236.0,0.0,18.40,1.00,0.5,2.34,0.00,1.0,25.74,NaN,NaN
2964621,2.0,2024-01-31 23:19:00,2024-01-31 23:38:00,NaN,3.33,NaN,None,211.0,25.0,0.0,19.97,0.00,0.5,0.00,0.00,1.0,23.97,NaN,NaN
2964622,2.0,2024-01-31 23:07:23,2024-01-31 23:25:14,NaN,3.06,NaN,None,107.0,13.0,0.0,23.88,0.00,0.5,5.58,0.00,1.0,33.46,NaN,NaN
2964623,1.0,2024-01-31 23:58:25,2024-02-01 00:13:30,NaN,8.10,NaN,None,138.0,75.0,0.0,32.40,7.75,0.5,7.29,6.94,1.0,55.88,NaN,NaN

In [6]:
import sklearn

In [7]:
sklearn.__version__

'1.6.1'